author: "Lucas"
title: "Lucas Mendelowski"
description: "I'm Lucas, an experienced software engineer focused on building web applications."
url: "https://www.mendelowski.com"
twitter: "lmendelowski"

autopages:
  enabled: false

collections:
  notes:
    output: true
    permalink: /til/:year/:month/:title
    sort_by: date
  posts:
    output: true
    permalink: /blog/:year/:month/:title


exclude:
  - package.json
  - package-lock.json
  - postcss.config.js

markdown: kramdown
highlighter: rouge
input: GFM

pagination:
  enabled: true
  per_page: 5
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 3
    after: 3

reading_time:
  second_plural: "sec"    # default: seconds
  minute_singular: "min"  # default: minute
  minute_plural: "min"

plugins:
  - jekyll-postcss-v2
  - jekyll-paginate-v2
